version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        depends_on:
            - gustavodcdamas
        build:
            context: ./
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./public:/var/www/public
            - ./public:/var/www/public/gustavodcdamas/
        networks:
            - net_local
            - geral

networks:
    net_local:
        driver: bridge
    geral:
        external: true
