version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--port", "6379", "--requirepass", "Mesa12Chuveiro67"]
    networks:
      - net_swarm
      - net_geral
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    external: true

networks:
  net_swarm:
    name: net_swarm
    external: true
    attachable: true
  net_geral:
    name: net_geral
    driver: bridge
    external: true
    attachable: true